Lesson 11
mixeeff/test-guru pull request #11
Opened 2019-02-27 22:59 UTC by mixeeff

2019-02-28 05:55 UTC, iBublik requested changes

2019-02-28 05:55 UTC, iBublik commented on app/controllers/admin/base_controller.rb
> +    redirect_to root_path, alert: 'Эта страница доступна только администратору' unless current_user.is_a?(Admin)
Проверку на то что юзер админ лучше вынести в модель

2019-02-28 05:55 UTC, iBublik commented on app/controllers/admin/tests_controller.rb
> +  def start
Этот экшн в контроллере админа не нужен

2019-02-28 05:55 UTC, iBublik commented on app/controllers/admin/tests_controller.rb
> +    @test.author_id = current_user.id
У тебя есть ассоциация `test_created` (почему единственное число?), используй ее для связи с автором

2019-02-28 05:55 UTC, iBublik commented on app/controllers/application_controller.rb
> +  def after_sign_in_path_for(resource)
Не используй абстрактный нейминг там, где можно написать более понятно. У нас единственным ресурсом является пользователь

2019-02-28 05:55 UTC, iBublik commented on app/controllers/application_controller.rb
> +    if current_user.is_a?(Admin)
Используй параметр, который приходит в метод, а не current_user

2019-02-28 05:55 UTC, iBublik commented on app/controllers/registrations_controller.rb
> +  def sign_up_params
Не нужно для этого переопределять контроллер - https://github.com/plataformatec/devise#strong-parameters

2019-02-28 05:55 UTC, iBublik commented on app/controllers/sessions_controller.rb
> +   after_action :welcome_message, only: :create
Можно просто определить экшн `create`:
```ruby
def create
   super
   flash[] = ...
```

2019-03-01 03:34 UTC, max-underthesun commented on app/controllers/admin/tests_controller.rb
> +    @test.author = current_user
Артем вот в [этом комментарии](https://github.com/mixeeff/test-guru/pull/11#discussion_r261054175) подсказывал в прошлый раз использовать ассоциацию
имеется в виду такой вариант:
```ruby
@test = current_user.created_tests.new(test_params)
```

2019-03-01 03:34 UTC, max-underthesun commented on app/models/admin.rb
>  end
можно добавить валидации аттрибутов имя, фамилия
насколько я помню в скринкасте класс Админ этим отличался от класса Юзер

2019-03-03 16:35 UTC, merged