Answers model, Scaffold etc
mixeeff/test-guru pull request #9
Opened 2019-02-14 20:54 UTC by mixeeff

Lesson 9

2019-02-15 05:00 UTC, max-underthesun commented on app/models/test_passage.rb
> +  before_update :next_question
эти два коллбека делают одно и то же по сути
оба устанавливают следующий вопрос
разница лишь в том, что считать следующим вопросом, т.е разница в поиске этого следующего вопроса
имеет смысл объединить их в один простой коллбек:

```ruby
def set_current_question
  self.current_question = next_question
end
```
а всю различающуюся логику поместить уже в метод `next_question`

2019-02-15 05:00 UTC, max-underthesun commented on app/models/test_passage.rb
> +    end
однострочник с постфиксным `if` будет проще читаться

2019-02-15 05:00 UTC, max-underthesun commented on app/models/test_passage.rb
> +    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
здесь стоит еще учесть, что пользователь может не выбрать ни одного ответа из предложенных (в аргументах "нил") и код от этого не должен падать

2019-02-15 05:00 UTC, max-underthesun commented on app/views/test_passages/result.html.erb
> +  <% if @test_passage.test_result >= 85 %>
это бизнес-логика и ее правильно будет поместить в модель, а здесь оставить что-то типа:

```html
  <% if @test_passage.successful? %>
```

2019-02-15 05:00 UTC, max-underthesun commented on app/controllers/questions_controller.rb
> +    end
такую логику нужно помещать в модели, в коллбек

2019-02-15 05:00 UTC, max-underthesun commented on app/controllers/questions_controller.rb
> +    end
лучше использовать символ: `maximum(:sort_index)`

2019-02-15 05:00 UTC, max-underthesun commented on app/controllers/questions_controller.rb
> +    end
вообще ты пошел сложным путем
можно было пока обойтись сортировкой по "ай-ди" в рамках каждого теста и соответсвенно определением номера динамически, согласно этой сортировке... 
в общем-то функционал получится такой же как и у тебя - у тебя же тоже в порядке создания будет по сути номера присваиваться... т.е. ты как бы создаешь "внутренний ай-ди" для вопросов в скоупе теста

твое решение возможно более интересное, если понадобится менять порядок ответов в тесте
но надо будет дописать функционал, позволяющий это делать - нужно будет перенумеровывать часть ответов или все ответы при каждом изменении этого "внутреннего индекса" у любого из ответов

в общем я бы тебе рекомендовал обойтись использованием уже существующего индекса (дополнительное поле убрать), т.к. все равно у тебя этого дополнительного функционала нет, и текущее усложнение в итоге не имеет смысла

2019-02-15 05:00 UTC, max-underthesun commented on app/models/user.rb
> +    test_passages.order(id: :desc).find_by(test_id: test.id)
лучше `find_by(test: test)`

2019-02-15 05:00 UTC, max-underthesun commented on config/routes.rb
> +    end
когда всего одна строчка, проще написать
```ruby
post :start, on: :member
```

2019-02-16 06:27 UTC, iBublik requested changes

2019-02-16 06:27 UTC, iBublik commented on app/controllers/answers_controller.rb
> +  def edit; end
Экшны new/create edit/update обычно парами описываются, потому что один логически продолжает другой

2019-02-16 06:27 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    @answer.question_id = params[:question_id]
Зачем? Почему не сделать как в new?

2019-02-16 06:27 UTC, iBublik commented on app/controllers/answers_controller.rb
> +  before_action :set_answer, only: %i[show edit update destroy]
Соблюдай единообразие в нейминге - выше подобный коллбек называется find, здесь set

2019-02-16 06:27 UTC, iBublik commented on app/models/test_passage.rb
> +    test.questions.order(:id).ids.index(current_question.id) + 1
Неплохой вариант, но можно все упростить до одного запроса. Посмотри на то, как ищется следующий вопрос - здесь примерно такая же логика будет

2019-02-16 06:27 UTC, iBublik commented on app/models/test_passage.rb
> +    return correct_answers.count == 0 if answer_ids.nil?
Слишком сложно. Тебе всего лишь надо обеспечить, чтоб в answer_ids всегда был массив. Для этого есть метод `Array` - он преобразует значение в массив (`Array(answer_ids)`)

2019-02-16 06:27 UTC, iBublik commented on db/migrate/20190212221506_create_test_passages.rb
> +      t.references :current_question, foreign_key: true
По конвенции имя таблицы, на которую ссылается внешний ключ, берется из 1го параметра. Т.е. тут создается ключ к несуществующей таблице `current_questions`. Это почему-то работает на SQLite, но на серьезных СУБД вроде PostgreSQL вызовет ошибку. Нужно явно указать к какой таблице создавать внешний ключ

2019-02-18 19:57 UTC, merged